
package com.example.webservice.hangzhouplatlease.company.service.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RentQyServiceException", targetNamespace = "http://impl.service.company.hzfc.com")
public class RentQyServiceException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RentQyServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RentQyServiceException_Exception(String message, RentQyServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RentQyServiceException_Exception(String message, RentQyServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.hzfc.company.service.impl.RentQyServiceException
     */
    public RentQyServiceException getFaultInfo() {
        return faultInfo;
    }

}
