
package com.example.webservice.hangzhouplatlease.company.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RentQyService", targetNamespace = "http://impl.service.company.hzfc.com", wsdlLocation = "http://zlservice.tmsf.com/services/RentQyService?wsdl")
public class RentQyService
    extends Service
{

    private final static URL RENTQYSERVICE_WSDL_LOCATION;
    private final static WebServiceException RENTQYSERVICE_EXCEPTION;
    private final static QName RENTQYSERVICE_QNAME = new QName("http://impl.service.company.hzfc.com", "RentQyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://zlservice.tmsf.com/services/RentQyService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RENTQYSERVICE_WSDL_LOCATION = url;
        RENTQYSERVICE_EXCEPTION = e;
    }

    public RentQyService() {
        super(__getWsdlLocation(), RENTQYSERVICE_QNAME);
    }

    public RentQyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RENTQYSERVICE_QNAME, features);
    }

    public RentQyService(URL wsdlLocation) {
        super(wsdlLocation, RENTQYSERVICE_QNAME);
    }

    public RentQyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RENTQYSERVICE_QNAME, features);
    }

    public RentQyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RentQyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RentQyServicePortType
     */
    @WebEndpoint(name = "RentQyServiceHttpSoap11Endpoint")
    public RentQyServicePortType getRentQyServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://impl.service.company.hzfc.com", "RentQyServiceHttpSoap11Endpoint"), RentQyServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RentQyServicePortType
     */
    @WebEndpoint(name = "RentQyServiceHttpSoap11Endpoint")
    public RentQyServicePortType getRentQyServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.company.hzfc.com", "RentQyServiceHttpSoap11Endpoint"), RentQyServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RENTQYSERVICE_EXCEPTION!= null) {
            throw RENTQYSERVICE_EXCEPTION;
        }
        return RENTQYSERVICE_WSDL_LOCATION;
    }

}
