
package com.example.webservice.webserviceClient.automaticallyGenerate;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CxfService", targetNamespace = "http://webservice.example.com", wsdlLocation = "http://127.0.0.1:8081/services/CxfService?wsdl")
public class CxfService_Service
    extends Service
{

    private final static URL CXFSERVICE_WSDL_LOCATION;
    private final static WebServiceException CXFSERVICE_EXCEPTION;
    private final static QName CXFSERVICE_QNAME = new QName("http://webservice.example.com", "CxfService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8081/services/CxfService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CXFSERVICE_WSDL_LOCATION = url;
        CXFSERVICE_EXCEPTION = e;
    }

    public CxfService_Service() {
        super(__getWsdlLocation(), CXFSERVICE_QNAME);
    }

    public CxfService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CXFSERVICE_QNAME, features);
    }

    public CxfService_Service(URL wsdlLocation) {
        super(wsdlLocation, CXFSERVICE_QNAME);
    }

    public CxfService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CXFSERVICE_QNAME, features);
    }

    public CxfService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CxfService
     */
    @WebEndpoint(name = "CxfServiceImplPort")
    public CxfService getCxfServiceImplPort() {
        return super.getPort(new QName("http://webservice.example.com", "CxfServiceImplPort"), CxfService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxfService
     */
    @WebEndpoint(name = "CxfServiceImplPort")
    public CxfService getCxfServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.example.com", "CxfServiceImplPort"), CxfService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CXFSERVICE_EXCEPTION!= null) {
            throw CXFSERVICE_EXCEPTION;
        }
        return CXFSERVICE_WSDL_LOCATION;
    }

}
